/** Oxy UI theme — the exact tokens from the chosen Google Stitch design
 *  (design/stitch-ui.html). Bundled at build time so the classes render
 *  identically to the design and work offline (no CDN). */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb783",
        "on-primary": "#1000a9",
        outline: "#908fa0",
        "surface-container-lowest": "#0d0d15",
        "secondary-container": "#39485a",
        "on-surface": "#e4e1ed",
        "on-secondary": "#233143",
        "surface-container-low": "#1b1b23",
        "on-primary-container": "#0d0096",
        "surface-dim": "#13131b",
        surface: "#13131b",
        "on-background": "#e4e1ed",
        "on-surface-variant": "#c7c4d7",
        primary: "#c0c1ff",
        "on-secondary-container": "#a7b6cc",
        "surface-container-highest": "#34343d",
        "surface-bright": "#393841",
        error: "#ffb4ab",
        background: "#13131b",
        "inverse-primary": "#494bd6",
        "surface-container": "#1f1f27",
        tertiary: "#ffb783",
        secondary: "#b9c8de",
        "primary-fixed": "#e1e0ff",
        "surface-container-high": "#292932",
        "primary-container": "#8083ff",
        "inverse-surface": "#e4e1ed",
        "surface-variant": "#34343d",
        "outline-variant": "#464554",
        "brand-slate": "#0F172A",
        "brand-panel": "#1E293B",
        "brand-border": "#334155",
        "brand-indigo": "#6366F1",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      spacing: {
        base: "4px",
        gutter: "16px",
        md: "16px",
        xs: "4px",
        sm: "8px",
        "margin-desktop": "32px",
        xl: "32px",
        lg: "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "label-caps": ["JetBrains Mono"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
};
